In [13]:
import numpy as np
from numpy import random

In [165]:
def create_matrix(n_rows, n_columns):
    scores_array = random.uniform(1,10,size=(n_rows, n_columns))
    return scores_array
 

In [213]:
# Test function
scores = create_matrix(5,5)

print(scores)

[[4.73495049 6.44151575 7.15126838 4.77592325 7.27299556]
 [2.7254594  7.31459841 3.40411398 6.83562818 5.98255194]
 [8.10803135 2.9595435  5.41268742 9.95931229 5.54659843]
 [5.82781382 6.93689264 2.57646742 1.05189672 3.65742719]
 [6.26702358 4.13590436 6.87665647 1.60926555 3.58310877]]


In [214]:
def calculate_scores_for_prediction(scores_array, percent):
    scores_for_prediction = scores_array.copy()
    number_of_zeros = int(np.round((1-percent)*scores_array.shape[0]*scores_array.shape[1]))
    choices = np.random.choice(scores_array.size, number_of_zeros, replace=False)
    scores_for_prediction.ravel()[choices] = 0 
    
    return scores_for_prediction

In [223]:
# Test function
scores_predict = calculate_scores_for_prediction(scores, 0.9)

print(scores_predict)

[[4.73495049 6.44151575 7.15126838 4.77592325 7.27299556]
 [2.7254594  7.31459841 3.40411398 6.83562818 5.98255194]
 [8.10803135 2.9595435  5.41268742 9.95931229 5.54659843]
 [0.         6.93689264 2.57646742 1.05189672 3.65742719]
 [6.26702358 4.13590436 6.87665647 1.60926555 0.        ]]


In [183]:
def Jaccard_Similarity(x, y):
    intersection = len(set(x) & set(y))
    union = len(set(x) | set(y))
    return intersection/float(union)

In [184]:
# Test function
Jaccard_Similarity(np.array([1,3,5,6,7]), np.array([1,2,5,6,8]))

0.42857142857142855

In [185]:
def Dice_Similarity(x,y):
    intersection = len(set(x) & set(y))
    return (2*intersection)/(len(x) + len(y))

In [188]:
# Test function
Dice_Similarity(np.array([1,3,5,6,8]), np.array([1,2,5,6,8]))

0.8

In [189]:
def Cosine_Similarity(x,y):
    dot_product = np.dot(x,y)
    x_norm = np.linalg.norm(x)
    y_norm = np.linalg.norm(y)
    return dot_product/(x_norm*y_norm)

In [198]:
# Test function
Cosine_Similarity(np.array([1,3,5,6,8,99,45,56]), np.array([1,2,5,6,8,20,39,50]))

0.8043252633777073

In [199]:
def Adjusted_Cosine_Similarity(x,y):
    x_mean = np.mean(x)
    x_adjusted = x - x_mean
    
    y_mean = np.mean(y)
    y_adjusted = y - y_mean
    
    return Cosine_Similarity(x_adjusted, y_adjusted)

In [200]:
# Test function
Adjusted_Cosine_Similarity(np.array([1,3,5,6,8,99,45,56]), np.array([1,2,5,6,8,20,39,50]))

0.6523443743895786